## Shared keys
shared_keys_path = "example_data/keys"

## Data files: none for party 0

## Output and cache paths
output_dir = "out/party0"
cache_dir = "cache/party0"

## Computational paramters
local_num_threads = 4
memory_limit = 40000000000